# Generated by Django 4.1 on 2022-08-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciac_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('Grado1', models.TextField(null=True)),
                ('Instructor', models.TextField(null=True)),
                ('Grado2', models.TextField(null=True)),
                ('Piloto', models.TextField(null=True)),
                ('Grado3', models.TextField(null=True)),
                ('CoPiloto', models.TextField(null=True)),
                ('Grado4', models.TextField(null=True)),
                ('Observador', models.TextField(null=True)),
                ('Hora_Entrada', models.TimeField()),
                ('Hora_Salida', models.TimeField()),
                ('Horas', models.FloatField(null=True)),
                ('Calificacion', models.IntegerField(null=True)),
                ('IFR', models.FloatField(null=True)),
                ('NVR', models.FloatField(null=True)),
                ('Observaciones', models.TextField(null=True)),
                ('Tipoentrenamiento', models.TextField(null=True)),
                ('Fuerza', models.TextField(null=True)),
                ('Tipo', models.TextField(null=True)),
                ('Unidad', models.TextField(null=True)),
            ],
        ),
    ]
