"""
Django settings for ciac_set project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import secrets #importa utilerias del sistema operativo

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

#The config file must be in the same CWD as manage.py

#SECRET_KEY = os.getenv('SECRET_KEY')
SECRET_KEY='citw3618x#g1q@=m771-byms5yv*rr&8gglkmg9=*!%t8j%tm'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#IP permitidas
ALLOWED_HOSTS = [
                    'www.vuelossim.com',
                    '192.168.10.136'
                ]

# Application definition

INSTALLED_APPS = [
    #contains the core of the authentication framework,
    # and its default models.
    'django.contrib.admin',
    'django.contrib.auth',
    #is the Django content type system, which allows 
    # permissions to be associated with models you create.
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ciac_app',
    #crispy_forms
    'crispy_forms',
    #User_authen app
    'user_authen.apps.UserAuthenConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    #Manages sessions across requests
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    #Associates users with requests using sessions.
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ciac_set.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ciac_set.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_ROOT=os.path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

MEDI_ROOT= os.path.join(BASE_DIR, '') #Para poder cargar las imagenes en la URL

MEDIA_URL= 'imagenes/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

##############Configuracion SMTP#############################
#MEDIA_ROOT=os.path.join(BASE_DIR,'media')
#MEDIA_URL='/media/'

LOGIN_REDIRECT_URL='index'

EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
######################## Collega email id ############
EMAIL_HOST_USER='hey2shop.inc@gmail.com'
EMAIL_HOST_PASSWORD='Top-shop8529'
#
######################################################

#admins
ADMINS = [('Carlos Zapata','hey2shop.inc@gmail.com')]
